version: '3.4'

services:
  catalogdb:
      image: mongo

  basketdb:
      image: redis:alpine  

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

  basket.api2:
    image: ${DOCKER_REGISTRY-}basketapi2
    build:
      context: .
      dockerfile: Basket.API2/Dockerfile

volumes:
  mongo_data:

